import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import {Walkppl} from "../components/walkppl"
import coverimage from "../album_covers/gramophone__by_hemingwaycafe-4548.jpeg"

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Playlists</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header className={styles.header}>
      </header>

      <main className={styles.main}>
      <div className={styles.grid}>
          <div className={styles.card}>
            <img src={coverimage} width='100%' height='228px'/>
            <h2>Crying Happy Tears</h2>
            <p>Happy music for happy times.</p>
          </div>

          <div className={styles.card}>
            <img src="../album_covers/Paradise_Coldplay.jpeg" width='100%' height='228px'/>
            <h2>Drowning</h2>
            <p>Sad music for sad times.</p>
          </div>

          <div className={styles.card}>
            <img src="../album_covers/Paradise_Coldplay.jpeg" width='100%' height='228px'/>
            <h2>Boredom</h2>
            <p>I'm bored bro.</p>
          </div>

          <div className={styles.card}>
            <img src="../album_covers/Paradise_Coldplay.jpeg" width='100%' height='228px'/>
            <h2>Road Trip</h2>
            <p>Hurtling towards doom at 90mph.</p>
          </div>
        </div>
      </main>

      <footer className={styles.footer}>
        <Walkppl />
      </footer>
    </div>
  )
}
